apps/feeds/urls.py
from django.urls import path

from apps.feeds import views

app_name = "feeds"
urlpatterns = [
    path("myfeeds/", views.MyFeedList.as_view(), name="myfeeds"),
    path("bookmarks/", views.ItemBookmarkList.as_view(), name="bookmarks"),
    path("follow/", views.FollowFeed.as_view(), name="follow"),
    path("feed/<int:pk>", views.FeedDetail.as_view(), name="feed_detail"),
    path("updatefeeds/<int:pk>", views.UpdateFeed.as_view(), name="update_async"),
    path("unfollow/<int:pk>", views.UnfollowFeed.as_view(), name="unfollow"),
    path("item/<int:pk>", views.ItemDetail.as_view(), name="item_detail"),
]

apps/notifications/urls.py
from django.urls import path

from apps.notifications import views


app_name = "notifications"
urlpatterns = [
    path("notifications/", views.NotificationList.as_view(), name="notifications",),
    path(
        "notification/<int:pk>",
        views.NotificationDetail.as_view(),
        name="notification_detail",
    ),
]

apps/user/urls.py
import django.contrib.auth.views as auth_views
from django.urls import include, path
from stronghold.decorators import public

import apps.user.views as user_views


app_name = "user"
urlpatterns = [
    path("welcome/", public(user_views.Welcome.as_view()), name="welcome"),
    path("signup/", public(user_views.Signup.as_view()), name="signup"),
    path("login/", public(user_views.Login.as_view()), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
]

rss_scraper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from stronghold.decorators import public

import rss_scraper.views

urlpatterns = [
    path("", public(rss_scraper.views.Home.as_view()), name="home"),
    path("admin/", admin.site.urls),
    path("feeds/", include("apps.feeds.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("user/", include("apps.user.urls")),
]

rss_scraper/views.py
from django import shortcuts
from django.views.generic import View


class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return shortcuts.redirect("feeds:myfeeds")
        else:
            return shortcuts.redirect("user:welcome")

rss_scraper/templates/rss_scraper/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}<title>RSS Scraper</title>{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
        {% block sidebar %}
          <ul class="sidebar-nav">
            {% if user.is_authenticated %}
              <p class="text-info">Hi, {{ user.username|title }}!</p>
              <div class="list-group">
                {% if user.profile.get_unread_notifications_count == 0 %}
                <a href="{% url 'notifications:notifications' %}" class="list-group-item list-group-item-action list-group-item-secondary">Notifications </a>
                {% else %}
                  <a href="{% url 'notifications:notifications' %}" class="list-group-item list-group-item-action list-group-item-secondary">Notifications <span class="badge badge-danger badge-pill">{{ user.profile.get_unread_notifications_count }}</span></a>
                {% endif %}
                <a href="{% url 'feeds:myfeeds' %}" class="list-group-item list-group-item-action list-group-item-secondary">My Feeds</a>
                <a href="{% url 'feeds:bookmarks' %}" class="list-group-item list-group-item-action list-group-item-secondary">Bookmarks</a>
                <a href="{% url 'feeds:follow' %}" class="list-group-item list-group-item-action list-group-item-secondary">Follow Feed</a>
                <a href="{% url 'user:logout' %}" class="list-group-item list-group-item-action list-group-item-secondary">Logout</a>
                {% endif %}
              </div>
          </ul>
        {% endblock %}
        </div>
      <div class="col-sm-9">{% block content %}{% endblock %}
    </div>
  </div >
  </div>

  </body>
</html>