apps/user/urls.py
import django.contrib.auth.views as auth_views
from django.urls import include, path
from stronghold.decorators import public

import apps.user.views as user_views


app_name = "user"
urlpatterns = [
    path("welcome/", public(user_views.Welcome.as_view()), name="welcome"),
    path("signup/", public(user_views.Signup.as_view()), name="signup"),
    path("login/", public(user_views.Login.as_view()), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
]

rss_scraper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from stronghold.decorators import public

import rss_scraper.views

urlpatterns = [
    path("", public(rss_scraper.views.Home.as_view()), name="home"),
    path("admin/", admin.site.urls),
    path("feeds/", include("apps.feeds.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("user/", include("apps.user.urls")),
]

apps/user/views.py
import django.contrib.auth.forms as auth_forms
import django.contrib.auth.views as auth_views
from django import urls
from django.contrib import auth
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView


class Login(auth_views.LoginView):
    template_name = "user/login.html"


class Signup(CreateView):
    template_name = "user/signup.html"
    form_class = auth_forms.UserCreationForm
    success_url = urls.reverse_lazy("home")

    def form_valid(self, *args, **kwargs):
        resp = super().form_valid(*args, **kwargs)
        user = self.object
        auth.login(self.request, user)
        return resp


class Welcome(TemplateView):
    template_name = "user/welcome.html"

apps/user/templates/user/login.html
{% extends 'rss_scraper/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-info">Login</button>
  </form>
{% endblock %}

apps/user/templates/user/signup.html
{% extends 'rss_scraper/base.html' %}

{% block content %}
  <h2>Sign Up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

apps/user/templates/user/welcome.html
{% extends 'rss_scraper/base.html' %}

{% block content %}
  <div class="jumbotron text-center">
    <h1 class=block-title pb-2">
      Welcome To RSS Scraper!
    </h1>

    <a href="{% url 'user:signup' %}" class="btn btn-info" role="button"">Signup</a>
    <a href="{% url 'user:login' %}" class="btn btn-info" role="button">Login</a>
{% endblock %}